### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by Niknu** [qemus/qemu-arm#101]
### Is your question not already answered in the FAQ?

- [X] I made sure the question is not listed in the [FAQ](https://github.com/qemus/qemu-arm/blob/master/readme.md).

### Is this a general question and not a technical issue?

- [X] I am sure my question is not about a technical issue.

### Question

Hi I have tried to read the documentation from the qemu and try to search my why around the topic.
How can I use a .IMG file instead of a .ISO file.

When I tried to use a different volume as that is stated in the FAQ.
The result I get is:

![image](https://github.com/qemus/qemu-arm/assets/37380867/49d13cc0-e3f2-415f-96f8-d21664dc40db)

**Comment by Niknu** [comment]
When I try what you are saying I get this:


```
docker compose up 
[+] Building 0.0s (0/0)                                                                                                                                                                  
[+] Running 1/0
 ✔ Container qemu  Recreated                                                                                                                                                        0.1s 
Attaching to qemu
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/test/git/qemu-arm/data.img" to rootfs at "/storage/data.img": open o_path procfd: open /var/lib/docker/overlay2/f8698c5da82ceb950432bcb871d596bb0937e4b60b9b652717969e982039ec47/merged/storage/data.img: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```


The compose file look like this:

```
services:
  qemu:
    container_name: qemu
    image: qemux/qemu-arm
    volumes:
     - /home/test/git/qemu-arm/data.img:/storage/data.img
    environment:
      BOOT: "https://dl-cdn.alpinelinux.org/alpine/v3.19/releases/aarch64/alpine-virt-3.19.1-aarch64.iso"
      #ARGUMENTS: "-blockdev driver=raw,file.filename=/home/test/git/qemu-arm,file.locking=off,file.driver=file,node-name=disk"
      #ARGUMENTS: "-drive format=raw,file=test_system.qcow2"
      #ARGUMENTS: "-M virt -m 3024 -drive if=none,file=/home/test/git/qemu-arm/system.img,format=raw,id=hd0 -device virtio-blk-device,drive=hd0 -netdev user,id=net0 -device virtio-net-device,netdev=net0 -nographic"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    stop_grace_period: 2m

```

**Comment by Niknu** [comment]
After I did what you suggested I 
The output I got:

```
UEFI Interactive Shell v2.2
qemu  | EDK II
qemu  | UEFI v2.70 (Debian distribution of EDK II, 0x00010000)
qemu  | Mapping table
qemu  |      BLK0: Alias(s):
qemu  |           PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0)
Press ESC in 1 seconds to skip startup.nsh or any other key to continue.
```

The docker compose file I ran:
services:
  qemu:
    container_name: qemu
    image: qemux/qemu-arm
    volumes:
      - ${PWD}/storage:/storage
    environment:
      DISK_SIZE: "20GB"
      BOOT: ""
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    stop_grace_period: 2m

**Comment by Niknu** [comment]
I get this error on, so the same as previously 

```
UEFI Interactive Shell v2.2
qemu  | EDK II
qemu  | UEFI v2.70 (Debian distribution of EDK II, 0x00010000)
qemu  | Mapping table
qemu  |      BLK0: Alias(s):
qemu  |           PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0)
Press ESC in 1 seconds to skip startup.nsh or any other key to continue.
```

**Comment by Niknu** [comment]
No sadly I have it from OEM with there flavor so I can't give you that sorry.
I have tried to use an Kali image to [raspberry pi 5 - ARM] (https://kali.download/arm-images/kali-2024.2/kali-linux-2024.2-raspberry-pi5-arm64.img.xz), where I unpacked the file to be a .img file.

This gave me this error, I'm not sure if that changes the problem completely:

```
UEFI Interactive Shell v2.2
qemu  | EDK II
qemu  | UEFI v2.70 (Debian distribution of EDK II, 0x00010000)
qemu  | Mapping table
qemu  |       FS0: Alias(s):HD0a0b:;BLK1:
qemu  |           PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0)/HD(1,MBR,0x4333ACA2,0x800,0x7F800)
qemu  |      BLK0: Alias(s):
qemu  |           PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0)
qemu  |      BLK2: Alias(s):
qemu  |           PciRoot(0x0)/Pci(0xA,0x0)/Scsi(0x0,0x0)/HD(2,MBR,0x4333ACA2,0x80000,0x1D80000)
Press ESC in 1 seconds to skip startup.nsh or any other key to continue.
```

**Comment by Niknu** [comment]
Get this error - both on v2.09 + v2.10:

```
docker compose up 
[+] Building 0.0s (0/0)                                                                                                                                               
[+] Running 1/0
 ✔ Container qemu  Created                                                                                                                                       0.0s 
Attaching to qemu
qemu  | ❯ Starting QEMU for Docker v2.02...
qemu  | ❯ For support visit https://github.com/qemus/qemu-arm
qemu  | ❯ CPU: Intel Core TM i7 8665U CPU | RAM: 19/31 GB | DISK: 3 GB (ext4) | HOST: 5.4.0-150...
qemu  | 
qemu  | ❯ ERROR: No boot disk specified, set BOOT= to the URL of an ISO file.
qemu exited with code 64

```

docker-compose file:

```
services:
  qemu:
    container_name: qemu
    image: qemux/qemu-arm
    volumes:
      - ${PWD}/storage/data.img:/boot.img
    environment:
      DISK_SIZE: "20GB"
      BOOT: ""
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    stop_grace_period: 2m
```
